### ISSUE TITLE
Hybrid Phi-Mamba model weights

### ISSUE THREAD

**Issue by juankost** [goombalab/phi-mamba#5]
Hi, 

Would it be possible to release also the model weights for the Hybrid Phi-Mamba? It would be helpful to allow people to benchmark against your hybrid model as well

Many thanks!
Juan

**Comment by AvivBick** [comment]
It's on our Huggingface repo. Take a look [here](https://huggingface.co/goombalab/Hybrid-Phi-Mamba).

**Comment by juankost** [comment]
Thanks a lot, I had missed that. Maybe you could add the link in the Pretrained Weights section of the Readme of this repo, you only link to the Phi-Mamba weights there.
