### ISSUE TITLE
Transformers library version? error in evaluation 

### ISSUE THREAD

**Issue by juankost** [goombalab/phi-mamba#6]
I'm getting the following error when I try to run your example evaluation:

`TypeError: PhiForCausalLM.__init__() got an unexpected keyword argument 'strict'`

Looking at the code, the dependency seems to come from the transformers library. Which transformers library version are you using?
I'm using version: 4.45.2

Thanks for the info

**Comment by AvivBick** [comment]
We used `transformers==4.39.1`, where the `strict` parameter ensures all weight keys match. Since you’re using 4.45.2, which may not support `strict`, you can remove it, but ensure that the correct weights are loaded without it.
