### ISSUE TITLE
Clarification on the training schedule used for the final model

### ISSUE THREAD

**Issue by juankost** [goombalab/phi-mamba#7]
Hi, I'd like to ask ask about the exact training schedule used for the final Phi-Mamba model, as it's a bit unclear from the appendix A in the paper. Specifically, it is not clear to me if the WSD scheduler was used independently for each of the stages of the final model, or if you used it in the setting of a "continuous run" where you have multiple checkpoints. If it was not used independently (and was used as part of a "continuous run") then I do not understand the different LR specified for each stage.

Could you elaborate? 
Thanks

**Comment by AvivBick** [comment]
Thank you for the question!

The Phi-Mamba model’s training schedule was structured with the WSD scheduler applied independently for each stage. Each stage had distinct warmup, stable, and decay phases.

**Comment by juankost** [comment]
Thanks for the quick reply!
