### ISSUE TITLE
Missing Stage 3 Code for Weight Transfer and Knowledge Distillation

### ISSUE THREAD

**Issue by L-z-Chen** [goombalab/phi-mamba#8]
Hi team,

Thank you for sharing the code for the paper "Transformers to SSMs: Distilling Quadratic Knowledge to Subquadratic Models." The code for Stage 1 (Matrix Mixer Alignment) and Stage 2 (Hidden State Alignment) is very helpful for reproducing the initial steps. However, I noticed that the code for Stage 3 (Weight Transfer and Knowledge Distillation) is not available in the repository. According to the paper, this stage is essential for finalizing the student model through weight transfer and knowledge distillation, which is necessary for achieving the reported experimental results.

Thanks

**Comment by kevinli573** [comment]
Stage 3 can be viewed as regular weight transfer and teacher-knowledge distillation, which can be implemented by adjusting regular pretraining pipelines.
